[package]
name = "emulator"
version = "0.1.0"
authors = ["rbrincke <r.h.w.tenbrincke@gmail.com>"]

[lib]
name = "emulator"
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/demo/mod.rs"

[dependencies]
crossterm = "0.18"
rand = "0.7.3"
